### ISSUE TITLE
Re-enable motor after magnetic sensor detection

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/scitos_drivers#104]
Can someone tell me how to disable the motor stop after the magnetic sensor has detected a magnetic strip?

**Comment by Jailander** [comment]
Hi. There is a service for it but I can't remember right now the name I'm not at the lab will be in 20 mins, but if you have the latest version of scitos teleop the start button should call this service

**Comment by cdondrup** [comment]
Press start on the joy pad.
If that is not released, get the latest version. The service to call is something with barrier in it 😉

**Comment by ToMadoRe** [comment]
Thanks!
