### ISSUE TITLE
sick laser driver

### ISSUE THREAD

**Issue by cburbridge** [strands-project/scitos_drivers#21]
The care-o-bot driver for the S300 looks good (https://github.com/ipa320/cob_driver/tree/groovy_dev/cob_sick_s300), might be worth testing to see if the readings are less noisy with it than the ais-bonn driver.

**Comment by RaresAmbrus** [comment]
I can take a look at this, it will take a while though as the KTH robots haven't arrived yet.

**Comment by cdondrup** [comment]
On first glance it does not seem to make a difference. Both are equally noisy. I didn't have time to play with parameters yet so I can't give you a final result. But it doesn't look very promising.

**Comment by cburbridge** [comment]
Ok lets stick with this driver
