### ISSUE TITLE
Rename and restructure package

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_drivers#22]
Rather than create a new repo for the drivers, we should restructure this to be a proper catkin package for the drivers, moving out the other contained packages to appropriate packages as described by [the software organisation page](https://github.com/strands-project/strands-project.github.io/wiki/Software-organisation).

**Comment by marc-hanheide** [comment]
in addition, the scitos_description should be removed here as it conflicts now with scitos_common

**Comment by kunzel** [comment]
@marc-hanheide scitos_common is actually a meta-package (aka stack) and scitos_description is one package in scitos_common. Currently it is the only one, but potentially there is room for more (please confer pr2_common for other examples). I think it looks a little bit strange as packages cannot be nested anymore with catkin. But this is how it is I guess. What do you think?

**Comment by kunzel** [comment]
Oh, did you mean the 'old' scitos_description package in scitos_mira? Then I agree, it can e removed.

**Comment by marc-hanheide** [comment]
Yes, that's what I meant

**Comment by cburbridge** [comment]
I have restructured as discussed. However, this repository now needs renaming to "scitos_drivers" ASAP as the system will not work until this is done. I don't have GitHub permissions @hawesie @marc-hanheide

**Comment by marc-hanheide** [comment]
I have renamed it just now. @hawesie
