### ISSUE TITLE
Create new repository

### ISSUE THREAD

**Issue by cburbridge** [strands-project/scitos_drivers#25]
We need a new repo named 

"scitos_robot" : This stack collects SCITOS-specific components that are used in bringing up a robot. 

as discussed on the Software Management page on the wiki. I have insufficient privileges to create new repositories in strands? @hawesie ~ @marc-hanheide  please create it...

**Comment by marc-hanheide** [comment]
I can create it, originally I created a repository called "scitos" which currently only contains the stuff taken from the USB stick that came with the robot. I wonder if it is better to simply delete this and put the content somewhere else or to re-structure that one so it fits you needs. Opinions? @cburbridge, you choose. I could also add you to the owners, but @hawesie should have his say there.

**Comment by cburbridge** [comment]
I think change the name of the scitos => scitos_robot would be best. The content there could go into a folder in a some general data store.

**Comment by marc-hanheide** [comment]
agreed... done. I leave the reorganisation to you. 

https://github.com/strands-project/scitos_robot

I reckon we don't need this private, do we?

**Comment by cburbridge** [comment]
Public is no problem. Thanks Marc.
