### ISSUE TITLE
EyeLids doesn't work

### ISSUE THREAD

**Issue by cdondrup** [strands-project/scitos_drivers#37]
Just tried it on Linda but sadly: 

```
rostopic pub /head/commanded_state sensor_msgs/JointState "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
name: ['EyeLids']
position: [0]
velocity: [0]
effort: [0]" 
```

does nothing. Where as moving the eye lids separately still works. Or am I using it wrong?

**Comment by cburbridge** [comment]
That is strange. just tested and both this
`rostopic pub /head/commanded_state sensor_msgs/JointState '{ header: {frame_id:  }, name: ['EyeLids'], position: [10], velocity: [1], effort: [1]}'`
and the exact command you wrote work fine on Bob. Was there any error message from scitos_mira ?

**Comment by cdondrup** [comment]
Your absolutely right. It works fine.
System was updated regularly but not restarted. So the last changes didn't have any effect. Works now and I am slightly embarrassed... Don't tell it to anyone ;)
