### ISSUE TITLE
Laser driver: angle min == angle max?!

### ISSUE THREAD

**Issue by cdondrup** [strands-project/scitos_drivers#38]
This is part issue and part question:
I noticed yesterday that the angle_min and angle_max values are exactly the same in the /scan topic. So since the driver is not our code, does anyone have an idea why the code says:

```
scan_data_.angle_min = -(field_of_view_/4.0) / 180.f * M_PI;
scan_data_.angle_max = -(field_of_view_/4.0) / 180.f * M_PI;
```

Shouldn't it be a positive value for angle_max like in simulation?

**Comment by cburbridge** [comment]
Oops! The original code only published either the full scan, or a trimmed scan with FOV 180 degrees. I changed it to allow any field of view trimming a while back, as on the robots we can get considerably more than 180 degrees - only a little needs trimming. However, in doing so I made this bug.

**Comment by cdondrup** [comment]
Ah, ok. It still worked but just got me a bit confused. 
Thanks for fixing.
