### ISSUE TITLE
PTU JointState does not care about names

### ISSUE THREAD

**Issue by cdondrup** [strands-project/scitos_drivers#40]
I just noticed that the JointState message sent to /ptu/cmd is not parsed correctly. It will always take the first position argument as the pan and the second as the tilt even if the name field says something different. This leads to unwanted behaviour, e.g.:

```
rostopic pub /ptu/cmd sensor_msgs/JointState 
"header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
name: ['tilt']
position: [0.5]
velocity: [0.5]
effort: [0]"
```

will pan and not tilt.

**Comment by cburbridge** [comment]
Yes, I noticed this too. It makes it impossible to control the tilt join without sending a position for the pan joint. 
I'll fix it, but can't do it until Thursday.

**Comment by cburbridge** [comment]
The merged fix should solve this problem.
