### ISSUE TITLE
change MIRA parameters on the fly (exposed through ROS service or param)

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_drivers#50]
we would like to able to change the "force" parameter in MIRA on the fly to be able to go up and down our ramp safely. In general, we should expose the MIRA params through ROS params or a dedicated ROS service, whatever is more feasible. This has been suggested by @gestom and @Jailander.

**Comment by Jailander** [comment]
Is there any news if this is possible maybe now that @chmartin21 is at Birmingham it could be possible to have feedback on this

**Comment by cburbridge** [comment]
@chmartin21 is the force parameter controllable via a MIRA RPC call?

**Comment by marc-hanheide** [comment]
Again, I think @gestom implemented this, @Jailander ?

**Comment by Jailander** [comment]
again yes also in this PR https://github.com/strands-project/scitos_drivers/pull/82

**Comment by Jailander** [comment]
I will tell him that documentation is needed urgently

**Comment by marc-hanheide** [comment]
:+1: if no documentation is there, here's some insightful PR: https://github.com/strands-project/scitos_common/pull/48/files introducing the service to call for setting the force.
