### ISSUE TITLE
PTU Action Server Move

### ISSUE THREAD

**Issue by cburbridge** [strands-project/scitos_drivers#55]
I would like to move the flir_pantilt_d46 action server out of that package and into somewhere in scitos_apps. This is so that anything depending on it (metric maps, object instance checking) can be built and run on simulation machines without the scitos_drivers repo. @kunzel we talked about this a while ago..

There is already a PTU action server in scitos_apps: https://github.com/strands-project/scitos_apps/tree/hydro-devel/scitos_ptu

Is it ok to join these two together?  @RaresAmbrus  @nilsbore @kunzel @cdondrup @gestom Who/what uses them

**Comment by kunzel** [comment]
Sounds good to me

**Comment by nilsbore** [comment]
I only use the flir_pantilt_d46 action server. Since I had the problem of this being in scitos_drivers when I wanted to test it in simulation, I think this is a good thing™.

**Comment by nilsbore** [comment]
Note that https://github.com/strands-project/strands_morse/pull/64 has to be merged for it to actually work.

**Comment by nilsbore** [comment]
@cburbridge Close this?
