### ISSUE TITLE
Remove sick300

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_drivers#60]
We should now use the official ros version: https://github.com/bohlender/sicks300

**Comment by marc-hanheide** [comment]
yes, now that https://github.com/bohlender/sicks300/pull/2 has been merged.

**Comment by cburbridge** [comment]
is the official one packaged as a deb in the ros repositories?

**Comment by marc-hanheide** [comment]
Not sure, is it not? If it isn't we can fork it and package it ourselves.

**Comment by marc-hanheide** [comment]
it's not in the hydro repos. So I forked it and released it ourselves. See https://github.com/strands-project/rosdistro/pull/27

**Comment by marc-hanheide** [comment]
so... it seems it has now been successfully built. I think we can remove it now from here 

see build log: http://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-sicks300_binarydeb_precise_amd64/1/
