### ISSUE TITLE
remove flir package from this repo

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_drivers#61]
... and use the official release instead: http://wiki.ros.org/flir_ptu_driver

**Comment by cdondrup** [comment]
What about the changes made in: 1698d0b9bf76bd146f3af5e80276e278e74a02d0 ?

**Comment by marc-hanheide** [comment]
oh... you're right... I just checked if I can simply pull in these changes into a fork and file a pull request. But they official driver has been refactored massively, so I'd have to reimplement this, I suppose :angry: But I understand this was only needed for the memory game, was it? So, it's not urgent?

**Comment by cdondrup** [comment]
It's also used for some of the idle behaviour in the nhm system which increases it's urgency only slightly. Can we keep a copy of the current version somewhere to still be able to run the nhm system at PR events?

**Comment by marc-hanheide** [comment]
sure we can... but the change is so small that it would probably be easier to just reintroduce it into the official version.

**Comment by cdondrup** [comment]
Just thinking about our upcoming event.

**Comment by marc-hanheide** [comment]
That official driver is quite different in structure, topic names, etc. I'm not quite sure we want to invest effort at the minute to change everything for this driver as ours is working nicely. This really would mean quite a bit of refactoring IMO.

What's @cburbridge's and @hawesie's view on this?

If you agree not to do it, then please close as won't fix.

**Comment by cburbridge** [comment]
I agree, no real need to hurry this as long as it doesn't cause release
problems..

**Comment by marc-hanheide** [comment]
nope, it won't as the "official" one has a different name anyway.
