### ISSUE TITLE
prepare for release

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_drivers#62]
This repository needs a little work according to the plans outlined in https://github.com/strands-project/strands_management/wiki/software-distribution

Most importantly, we need to integrate the automatic use of MIRA (and to remove the flir and sick packages). MetraLabs have now released it under GPL and also provide binaries here: ftp://ftp.mira-project.org/repos/MIRA-main/ubuntu-1204lts-x64/base/

A simple option would be to build debian packages from the binaries and release them at our ubuntu repository at http://lcas.lincoln.ac.uk/repos/building/

Then we'd have to include a `rosdep` key for mira-base and refer that in `package.xml`. Alternatively, we simply provide installation instructions for MIRA, but that's less convenient. 

Once this is complete, the repository's dependencies should be checked and it should be released as outlined in https://github.com/strands-project/strands_management/wiki/STRANDS-release-procedures

**Comment by cburbridge** [comment]
I can't see the scitos robot packages in the open source MIRA release, only the MIRA framework. Am I missing something?

**Comment by marc-hanheide** [comment]
You're right... We should enquire with MetraLabs if we'd be allowed to put
debs up for that one.

**Comment by marc-hanheide** [comment]
update: I have now released a MIRA version and have updated and released a first version of `scitos_drivers` accordingly to use it. 

There is a [MIRA debian "packager"](https://github.com/strands-project/dh_bin_wizard) which creates an Ubuntu package named [`mira-scitos`](http://lcas.lincoln.ac.uk/repos/building/pool/main/m/mira-scitos/) with a full MIRA install and all SCITOS packages. This is installed into `/opt/mira-scitos` when `sudo apt-get install mira-scitos` has been called. The package `scitos_mira` depends on this package, obviously. I tested on my machine and it works nicely. It would be much appreciated if someone like @Jailander @cburbridge @cdondrup or somebody at BHAM nominated by @hawesie could test this on the real robot at some point. Simply run `sudo apt-get install ros-hydro-scitos-drivers` and then you should be able to `roslaunch scitos_mira scitos_mira.launch`
