### ISSUE TITLE
Add support for magnetic strip detection

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_drivers#73]
We need the mira driver to support the detection and reseting of magnetic floor tape in time for the marathon. @cburbridge and @creuther will look at it.

**Comment by marc-hanheide** [comment]
I think @gestom did this (His github interface @Jailander to report ;-) )

**Comment by Jailander** [comment]
yes @gestom did it and was merged on this pull request https://github.com/strands-project/scitos_drivers/pull/82

**Comment by Jailander** [comment]
This was an auto message as he is not here

**Comment by marc-hanheide** [comment]
so, let's close it with some documentation that @gestom posted on https://github.com/strands-project/scitos_common/pull/49:

> The magnetic stripe detector actually diquises itself as an RFID detector reading an RFID tag with a specific code. Therefore, I made a service that allows the RFID device to be switched on and off, a topic that provides the RFID tag (/rfid) codes and a topic that tells you if an RFID tag with the code that corresponds to the magnetic stripe has been detected (/magnetic_barrier). I am not 100% sure if the robot has an actual RFID detector, but the MIRA center says so. See also the mail from Thomas F. from 22/04.

**Comment by creuther** [comment]
On Bob, we had the problem that the relevant Main Control Unit (MCU) flag for using the magnetic sensor wasn't set by MetraLabs. As the relevant tools aren't publicly available as well, here is a guide on using the "low level tools" to enable the flag: 
(make sure that no instance of MIRA is accessing the CAN bus)

> cd /opt/MIRA-commercial/bin
> ./scitosSDOTool /dev/ttyUSB2 read uint8 0x04 0x2005 0x12

This will yield the current value of this register. If it is 0x90, everything's peachy. If it is 0x80, we need to set the value to 0x90:

> ./scitosSDOTool /dev/ttyUSB2 write uint32 0x04 0x2000 0x0c 0xf2671d4a
> ./scitosSDOTool /dev/ttyUSB2 write uint8 0x04 0x2005 0x12 0x90

The first command will lift the write lock of the control register 0x04 -> 0x2005 -> 0x12 (magic!) and the second one will persistently change the value. Beware that the write lock will only be lifted for a **very short period of time** so have the commands in the bash history for quick executing or better yet "and" them (&&).

Verify that the value was set correctly by using the first command:

> ./scitosSDOTool /dev/ttyUSB2 read uint8 0x04 0x2005 0x12

Any trouble, give me a shout.
