### ISSUE TITLE
EBC Power shutting off?

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/scitos_drivers#75]
So it's our switch again. It's connected to the EBC-0 port in the same place as the cables that go up to the head and are supposed to power the Manta stereo-cameras. That's the 12V slot.

Sometimes, seemingly randomly, that specific EBC port shuts off. Most of the time, it's only the EBC-0 12V, the others (6V and 24V) are still running.

One way I can reproduce this is using the docking tool `rosrun actionlib axclient.py /chargingServer` and sending a `charge` command. At the end of the command, it shuts off. If I send that command again while it's off, it turns on again and, at the end of the command, shuts off again.

Note that this is just one way. Sometimes it seems to randomly shut off, but probably I just didn't notice the pattern yet.

At first I thought it happens when there's a lot of traffic on the switch and it needs too much power, but I don't think that's it as I can stream both xtion videos without any problem.

I'm like wtf O.o any help appreciated!

**Comment by cdondrup** [comment]
That is because Linda has a lamp on this Port and @gestom is reconfiguring it during docking to turn on the light and turns it off afterwards.

**Comment by lucasb-eyer** [comment]
Oh well, this is [programmed behavior](https://github.com/strands-project/scitos_apps/blob/hydro-devel/scitos_docking/src/scitos_docking/CLightClient.cpp#L19).

@gestom you wrote that line. Did you put a light in there and just hardcode it to that EBC port? We put our switch on that port. Next time we meet, I'll kick you for that!

**Comment by lucasb-eyer** [comment]
Heh, talk about timing.

**Comment by cdondrup** [comment]
Same behaviour cost us a day before the deployment in Vienna because the PTU was connected to that port...

**Comment by lucasb-eyer** [comment]
working on a fix...

**Comment by lucasb-eyer** [comment]
Gonna be fixed in strands-project/scitos_apps#119. Closing this until I can reproduce the other shutting off I got some times.
